/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        paper:  'var(--paper)',
        paper2: 'var(--paper-2)',
        paper3: 'var(--paper-3)',
        paper4: 'var(--paper-4)',
        line:   'var(--line)',
        line2:  'var(--line-2)',
        ink:    'var(--ink)',
        ink2:   'var(--ink-2)',
        ink3:   'var(--ink-3)',
        ink4:   'var(--ink-4)',
        accent:      'var(--accent)',
        'accent-soft': 'var(--accent-soft)',
        'accent-ink':  'var(--accent-ink)',
        'ok-bg':   'var(--ok-bg)',
        'ok-ink':  'var(--ok-ink)',
        'warn-bg': 'var(--warn-bg)',
        'warn-ink':'var(--warn-ink)',
        'late-bg': 'var(--late-bg)',
        'late-ink':'var(--late-ink)',
        // Legacy aliases so existing code doesn't break
        lime:        'var(--accent)',
        'lime-bg':   'var(--accent-soft)',
        'lime-ink':  'var(--accent-ink)',
        red:         'oklch(0.55 0.2 25)',
        'red-bg':    'oklch(0.95 0.04 25)',
        'red-ink':   'oklch(0.42 0.18 25)',
        amber:       'oklch(0.72 0.18 75)',
        'amber-bg':  'oklch(0.96 0.05 75)',
        'amber-ink': 'oklch(0.45 0.14 75)',
        teal:        'oklch(0.62 0.17 155)',
        'teal-bg':   'oklch(0.96 0.04 155)',
        'teal-ink':  'oklch(0.42 0.12 155)',
        blue:        'oklch(0.6 0.18 255)',
        'blue-bg':   'oklch(0.95 0.04 255)',
        'blue-ink':  'oklch(0.42 0.16 255)',
      },
      fontFamily: {
        sans:    ['Geist', 'Inter', 'system-ui', 'sans-serif'],
        serif:   ['Fraunces', 'Georgia', 'serif'],
        mono:    ['JetBrains Mono', 'ui-monospace', 'monospace'],
        display: ['Fraunces', 'Georgia', 'serif'],
      },
      boxShadow: {
        card:       'var(--shadow-card)',
        'card-hover': '0 4px 24px oklch(0.2 0.01 60 / 0.14)',
        pop:        'var(--shadow-pop)',
        'lime-glow': '0 0 0 3px var(--accent-ring)',
      },
      borderRadius: {
        sm: 'var(--r-sm)',
        md: 'var(--r-md)',
        lg: 'var(--r-lg)',
        xl: 'var(--r-xl)',
      },
      keyframes: {
        cardIn:    { from: { opacity: '0', transform: 'translateY(6px)' },             to: { opacity: '1', transform: 'none' } },
        overlayIn: { from: { opacity: '0' },                                            to: { opacity: '1' } },
        modalIn:   { from: { opacity: '0', transform: 'scale(0.97) translateY(6px)' }, to: { opacity: '1', transform: 'none' } },
        pulseDot:  { '0%,100%': { opacity: '1', transform: 'scale(1)' }, '50%': { opacity: '.5', transform: 'scale(0.7)' } },
        toastUp:   { from: { opacity: '0', transform: 'translateY(14px)' },            to: { opacity: '1', transform: 'none' } },
        shimmer:   { from: { backgroundPosition: '200% 0' },                           to: { backgroundPosition: '-200% 0' } },
      },
      animation: {
        'card-in':    'cardIn .4s both',
        'overlay-in': 'overlayIn .2s ease',
        'modal-in':   'modalIn .25s cubic-bezier(.2,.8,.2,1)',
        'pulse-dot':  'pulseDot 1.2s ease-in-out infinite',
        'toast-up':   'toastUp .25s ease',
        'shimmer':    'shimmer 2.2s linear infinite',
      },
    },
  },
  plugins: [],
}
